# Generated by Django 6.0 on 2025-12-09 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza', models.CharField(max_length=50, verbose_name='No. Póliza')),
                ('nombre_contratante', models.CharField(max_length=250)),
                ('sobrenombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='F: DD/MM/AAAA', null=True, verbose_name='Fecha de Nacimiento')),
                ('asegurado_principal', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_nacimiento_asegurado', models.DateField(blank=True, null=True, verbose_name='F. Nac. Asegurado')),
                ('producto', models.CharField(choices=[('alfa_medical_flex', 'Alfa Medical Flex'), ('integro', 'Integro'), ('pleno', 'Pleno'), ('practico', 'Practico'), ('imagina_ser_55', 'Imagina Ser 55'), ('imagina_ser_60', 'Imagina Ser 60'), ('imagina_ser_65', 'Imagina Ser 65'), ('imagina_ser_70', 'Imagina Ser 70'), ('legado', 'Legado'), ('nuevo_plenitud', 'Nuevo Plenitud'), ('objetivo_vida', 'Objetivo Vida'), ('orvi_6', 'ORVI 6'), ('orvi_10', 'ORVI 10'), ('orvi_15', 'ORVI 15'), ('orvi_20', 'ORVI 20'), ('realiza_creciente', 'Realiza Creciente'), ('segubeca', 'Segubeca'), ('tempo_vida', 'Tempo Vida'), ('temporal', 'Temporal'), ('vida_joven', 'Vida Joven'), ('vida_mil', 'Vida Mil'), ('vida_mujer', 'Vida Mujer'), ('vida_plena', 'Vida Plena'), ('visualiza', 'Visualiza')], max_length=100)),
                ('estatus_cliente', models.CharField(choices=[('en_vigor', 'En Vigor'), ('anulada', 'Anulada')], default='en_vigor', max_length=20)),
                ('deduce', models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], max_length=20, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, choices=[('peso', 'Peso'), ('udi', 'UDI'), ('usd', 'USD')], max_length=20, null=True)),
                ('modo_pago', models.CharField(blank=True, choices=[('agente', 'Agente'), ('directo', 'Directo'), ('tdc', 'TDC'), ('tdd', 'TDD')], max_length=50, null=True, verbose_name='Modo de Pago')),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo_pago', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=50, null=True)),
                ('dia_cobro', models.PositiveIntegerField(blank=True, null=True)),
                ('rechazo', models.BooleanField(blank=True, default=False, null=True)),
                ('intentos', models.IntegerField(blank=True, default=0, null=True)),
                ('amparado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_beneficiario', models.CharField(max_length=200)),
                ('fecha_nacimiento_beneficiario', models.DateField(blank=True, null=True)),
                ('parentesco', models.CharField(blank=True, choices=[('madre', 'Madre'), ('padre', 'Padre'), ('hijo', 'Hijo'), ('hija', 'Hija'), ('hermano', 'Hermano'), ('hermana', 'Hermana'), ('esposo', 'Esposo'), ('esposa', 'Esposa'), ('nieto', 'Nieto'), ('nieta', 'Nieta'), ('sobrino', 'Sobrino'), ('sobrina', 'Sobrina'), ('primo', 'Primo'), ('prima', 'Prima'), ('tutor', 'Tutor'), ('tutora', 'Tutora'), ('pareja', 'Pareja'), ('abuelo', 'Abuelo'), ('abuela', 'Abuela'), ('ninguno', 'Ninguno')], max_length=25, null=True)),
                ('estatus_beneficiario', models.CharField(blank=True, choices=[('asegurado', 'Asegurado'), ('beneficiario', 'Beneficiario')], default='beneficiario', max_length=25, null=True)),
                ('nombre_contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='cliente.cliente')),
            ],
        ),
    ]
